map! vv <esc>
set nu
set showcmd
set cin
syntax on
filetype on
set smartindent
set tabstop=4
set softtabstop=4
set cindent shiftwidth=4
set ai
set fileencoding=utf8
set fileencodings=utf8,cp936,gb2312,utf-16,big5

" no backup
set nobackup


" color scheme in GUI
if has('gui_running')
	syntax enable
    set background=dark
	colorscheme solarized
else
	" colorscheme torte
    "set background=light
endif


" taglist  :Tlist
let Tlist_Show_One_File=1     "不同时显示多个文件的tag，只显示当前文件的 
let Tlist_Exit_OnlyWindow=1   "如果taglist窗口是最后一个窗口，则退出vim   
let Tlist_Ctags_Cmd="ctags"   "将taglist与ctags关联

" omnicppcomplete
set nocp
filetype plugin on
map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

"english language ui
set langmenu=en_US
let $LANG = 'en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

"neocomplcache
let g:neocomplcache_enable_at_startup=1
let g:neocomplcache_enable_auto_select=1

"font
set guifont=Consolas:h10

